config/routes.rb
FirstApplication::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  match '/home', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/home',  :to => 'users#home'
  match '/signup',  :to => 'users#new'
  resources :microposts, :users

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#signout'

root :to => "pages#home"

end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer(4)      not null, primary key
#  content    :string(255)
#  user_id    :integer(4)
#  created_at :datetime
#  updated_at :datetime
#

class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :presence =>true
#  validates :content, :presence =>true, :length => { :maximum => 20, :minimum => 10}
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.xml
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.xml
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.xml
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.xml
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to(@micropost, :notice => 'Micropost was successfully created.') }
        format.xml  { render :xml => @micropost, :status => :created, :location => @micropost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @micropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.xml
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to(@micropost, :notice => 'Micropost was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @micropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.xml
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to(microposts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
   def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private
#
#    def wrap_long_string(text, max_width = 30)
#      zero_width_space = "&#8203;"
#      regex = /.{1,#{max_width}}/
#      (text.length < max_width) ? text :
#                                  text.scan(regex).join(zero_width_space)
#    end

end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table border="1">
  <tr bgcolor="black">
    <th><font color="white"><b>Content</b></font></th>
    <th><font color="white"><b>User</b></font></th>
    <th colspan="2"><font color="white"><b>Action</b></font></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td colspan="3" bgcolor="black"><%= link_to 'Show', micropost %><font color="white"> | </font>
    <%= link_to 'Edit', edit_micropost_path(micropost) %> <font color="white"> | </font>
<%= link_to 'Destroy', micropost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
  <tr bgcolor="black"><td colspan="4"><%= link_to '<< New Micropost', new_micropost_path %></td></tr>

</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<table border="1">

<font color="green"><%= notice %></font>
  <tr bgcolor="black">
    <td>
  <b><font color="white">Content:</font></b>
    </td>
    <td>
 <b><font color="white">User:</font></b>

</td>
 <td>
  <b><font color="white">Action:</font></b>
    </td>
  </tr>
  <tr>
    <td>
       <font color="black"> <%= @micropost.content %></font>
    </td>
     <td>
       <font color="black"> <%= @micropost.user_id %></font>
    </td>
    <td bgcolor="black">
<%= link_to 'Edit', edit_micropost_path(@micropost) %> <font color="white"><b> | </b></font>
<%= link_to 'Back', microposts_path %>
    </td>
  </tr>
</table>